// ✅ ChatAction.jsx
export const FETCH_CHAT_LIST = "FETCH_CHAT_LIST"
export const CHAT_USER_LIST = "CHAT_USER_LIST"
export const FETCH_CHAT_MESSAGES = "FETCH_CHAT_MESSAGES"
export const CLEAR_CHAT_MESSAGES = "CLEAR_CHAT_MESSAGES"

export const FETCH_CHAT_HISTORY = "FETCH_CHAT_HISTORY"
export const CHAT_HISTORY_LIST = "CHAT_HISTORY_LIST"

export const ADD_OR_UPDATE_MESSAGE = "ADD_OR_UPDATE_MESSAGE"
export const RESET_UNSEEN_COUNT = "RESET_UNSEEN_COUNT"
export const MARK_MESSAGES_SEEN = "MARK_MESSAGES_SEEN"
