export const FETCH_TEMPLATE_REQUEST = "FETCH_TEMPLATE_REQUEST"
export const TEMPLATE_DATA = "TEMPLATE_DATA"

export const FETCH_RECENTTEMPLATE_REQUEST = "FETCH_RECENTTEMPLATE_REQUEST"
export const RECENTTEMPLATE_DATA = "RECENTTEMPLATE_DATA"

export const RECENT_TEMPLATE_DELETE = "RECENT_TEMPLATE_DELETE"
